<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_register</name>
   <tag></tag>
   <elementGuidId>dd10b7fb-54be-49ad-afba-c984220290be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='um-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#um-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3018670-60b5-4988-8f41-b4592762619e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f416eba2-9985-49bc-b261-7328ba852fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>e28ba53e-b2a9-4b3e-8cf2-0bcc157a291b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-button</value>
      <webElementGuid>87a4c35f-8988-4643-84cb-43745630aaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um-submit-btn</value>
      <webElementGuid>1b9f6fec-a09d-4439-949c-5cfad85eaff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-submit-btn&quot;)</value>
      <webElementGuid>17f4d5b2-6cce-4bdc-8f55-f79de96fc13c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='um-submit-btn']</value>
      <webElementGuid>28ac5b69-9fad-4a39-ac6a-d8416634238f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-301']/div/figure/table/tbody/tr/td/div/div/form/div[2]/div/input</value>
      <webElementGuid>b55a900f-2660-4d39-83f0-4a40e1e309de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0ec0b01c-1bc3-478b-ae02-dd675f7523dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'um-submit-btn']</value>
      <webElementGuid>e5dfda1c-ea89-4254-b047-47ad4b76df19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
