<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Place order_blockUI blockOverlay</name>
   <tag></tag>
   <elementGuidId>8cebbd32-02cd-4ab1-994c-dc104eae1b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-54']/div/div/form[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.blockUI.blockOverlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>032684e3-425c-4886-bee6-e4f30a6f3193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blockUI blockOverlay</value>
      <webElementGuid>efdbfbfe-bb4b-4558-8e25-526cd8409606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;checkout woocommerce-checkout processing&quot;]/div[@class=&quot;blockUI blockOverlay&quot;]</value>
      <webElementGuid>72ef07d7-0f62-4a1e-b389-e2c59eb7db0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/div/div/form[2]/div[4]</value>
      <webElementGuid>8f8dc244-367f-4495-83e0-807eb8ca21fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[4]</value>
      <webElementGuid>9e2401f1-c2ec-4bae-b195-f1ccc760a72c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
