<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Newsletter</name>
   <tag></tag>
   <elementGuidId>2221fcec-7303-4d96-93a6-fe0405cfc475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='text-5']/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.textwidget > h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>fcfcf4b1-46c9-463c-aa8f-3ae68de427a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Newsletter
</value>
      <webElementGuid>b3b4e92f-2930-4d29-8f4f-4da82ab88629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-5&quot;)/div[@class=&quot;textwidget&quot;]/h3[1]</value>
      <webElementGuid>37485cad-da29-4eee-aa8a-7986cfefc7df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='text-5']/div/h3</value>
      <webElementGuid>03b51230-6e03-4f4a-97a8-b853752432ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[7]/following::h3[1]</value>
      <webElementGuid>6cb8d7df-b57e-416a-b7e5-9c51725534be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick View'])[7]/following::h3[1]</value>
      <webElementGuid>69348c9d-10a9-4207-8343-0c91cfc11299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/h3</value>
      <webElementGuid>1aab0af5-37c2-49af-8feb-933fab63e47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Newsletter
' or . = 'Newsletter
')]</value>
      <webElementGuid>b0664719-459b-4e78-8351-38dedd84f682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
