<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thanks for joining our email list</name>
   <tag></tag>
   <elementGuidId>bd3db000-8734-4090-8de4-4a5e582cd85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpforms-confirmation-291']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wpforms-confirmation-291</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fa1d704-faf8-4e3a-8de4-83bf39449b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-confirmation-container-full wpforms-confirmation-scroll</value>
      <webElementGuid>5664dc5c-47f5-4a9f-b601-1f5f746986af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-confirmation-291</value>
      <webElementGuid>5948f0ff-6fbd-464a-b4a4-1aa329d7001e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for joining our email list!
</value>
      <webElementGuid>b6f986d2-ccb6-4587-b9ba-9845d18e4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-confirmation-291&quot;)</value>
      <webElementGuid>ae2d9ef2-561a-41c8-a90c-3a560085ac82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wpforms-confirmation-291']</value>
      <webElementGuid>865bdf86-6adf-4431-b4fa-c0b625cc7656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-291']/div</value>
      <webElementGuid>fd8a63da-5de6-4ffd-8617-288a3810522c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/following::div[2]</value>
      <webElementGuid>20ec43c3-1799-424c-ba12-4fbc2151f583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[7]/following::div[11]</value>
      <webElementGuid>dd5f8235-1aae-428d-a2c6-0ceb5309163c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地図&amp;アクセス方法'])[1]/preceding::div[1]</value>
      <webElementGuid>1d342110-895b-4d2f-ba0f-a187de42a2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[1]/preceding::div[4]</value>
      <webElementGuid>ecc6f98c-85ab-4e31-b401-d09c3244d2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>e3dc9316-436d-4ec3-bd29-a4d82bb107c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wpforms-confirmation-291' and (text() = 'Thanks for joining our email list!
' or . = 'Thanks for joining our email list!
')]</value>
      <webElementGuid>afc864d4-4c19-400d-8481-facaec0394af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
