<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_27ab4d</name>
   <tag></tag>
   <elementGuidId>eeca3138-c257-4c69-93f5-67c586700acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-150x150.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-thumbnail.size-thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c160e22-ef42-447f-8c4d-6dfcf88452fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>baf42ec6-c664-4a9e-82d4-094ad0685362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>cf314946-8b25-4f3e-b5f1-fb36b3e59c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-150x150.jpg</value>
      <webElementGuid>1b269ebc-5ba6-4101-a8dc-93dac4702655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-thumbnail size-thumbnail</value>
      <webElementGuid>93c0178b-b614-4323-95c7-8d80139baca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3a0b6da6-a64a-41ac-a4bd-a9935f9ecc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-150x150.jpg 150w, https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-100x100.jpg 100w</value>
      <webElementGuid>3fa48315-2a14-4e08-a4f5-c0147965965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 150px) 100vw, 150px</value>
      <webElementGuid>2644a8a6-d8c0-4f40-8e10-ac1842eb0c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js_active vc_desktop vc_transform vc_transform&quot;]/body[@class=&quot;home page-template-default page page-id-152 page-child parent-pageid-150 wp-embed-responsive theme-the-hanger woocommerce-js wpb-js-composer js-comp-ver-6.7.0 vc_responsive site-main-font header-layout-full content-layout-full page-without-title footer-layout-boxed&quot;]/div[@class=&quot;site-wrapper&quot;]/header[@class=&quot;site-header site-header-style-1 header-normal&quot;]/div[@class=&quot;row small-collapse&quot;]/div[@class=&quot;small-12 columns&quot;]/div[@class=&quot;header-content&quot;]/div[@class=&quot;header-line-1&quot;]/div[@class=&quot;row align-middle&quot;]/div[@class=&quot;small-12 medium-8 large-9 columns&quot;]/div[@class=&quot;header-line-1-wrapper&quot;]/div[@class=&quot;header-search&quot;]/form[@class=&quot;header_search_form active&quot;]/div[@class=&quot;header_search_ajax_results_wrapper visible animated&quot;]/div[@class=&quot;header_search_ajax_results&quot;]/div[@class=&quot;ajax_results_wrapper&quot;]/div[@class=&quot;product-search-result&quot;]/a[1]/div[@class=&quot;product-search-img&quot;]/img[@class=&quot;attachment-thumbnail size-thumbnail&quot;]</value>
      <webElementGuid>0146dc53-ad6a-471b-8aac-762467f03ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-150x150.jpg')]</value>
      <webElementGuid>6032c04a-5e79-44fb-b70b-368e18354194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>6f531537-09e8-4202-8995-37f671dce42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-150x150.jpg']</value>
      <webElementGuid>0900173d-bf13-44bf-b19c-b6bd979407b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
