<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wpformsfields1</name>
   <tag></tag>
   <elementGuidId>42482491-db39-445d-8762-e8d2b0954d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-291-field_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wpforms-291-field_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4eee416-f284-4701-a0d7-dee6016eae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2585a047-9458-4e41-a367-6c34abe9c5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-291-field_1</value>
      <webElementGuid>6aa55c7f-54b4-4faf-992c-a66a90c91009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required</value>
      <webElementGuid>903365f1-f14b-4c43-9d96-32609b39936d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>c1f7bffc-dec3-40a4-8713-1837012cb77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-291-field_1&quot;)</value>
      <webElementGuid>620d1822-f012-48b2-ad4c-1f27c8daa94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-291-field_1']</value>
      <webElementGuid>0bb4df59-7d5d-4f82-9eff-e6aa1ce4807e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-291-field_1-container']/input</value>
      <webElementGuid>f3dc78df-7833-4fbc-b3eb-858c7ee06ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>73e99e0f-7529-41e1-b5a1-d0cbe362e48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wpforms-291-field_1' and @name = 'wpforms[fields][1]']</value>
      <webElementGuid>777d6881-9db1-4e2a-91c3-518047349b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
